### ISSUE TITLE
Broken hyperlink on turpial-firmware github page

### ISSUE THREAD

**Issue by GlenCooper** [btcven/turpial-firmware#111]
**Describe the bug**
On https://github.com/btcven/turpial-firmware when you click on the hyperlink for "CONTRIBUTING.md", it goes to a a 404 page

**To Reproduce**
1. Go to 'https://github.com/btcven/turpial-firmware'
2. Scroll down to Development Workflow
3. Click on "CONTRIBUTING.md"
4. See error at link destination https://github.com/btcven/turpial-firmware/blob/master/blob/master/CONTRIBUTING.md

**Expected behavior**
Anything would be better than a 404 page

**Screenshots**
![Screenshot from 2020-03-06 10-42-14](https://user-images.githubusercontent.com/967793/76077166-1b8b4080-5f98-11ea-97dd-d40916da7ac5.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser: Firefox
 - Version: 73.0.1 (64-bit)

**Additional context**
Awesome project.  I want to help.

**Comment by GlenCooper** [comment]
This is what I see at https://github.com/btcven/turpial-firmware/blob/master/blob/master/CONTRIBUTING.md

![Screenshot from 2020-03-06 10-51-54](https://user-images.githubusercontent.com/967793/76077411-8b013000-5f98-11ea-8185-f317a4272ec1.png)

**Comment by jeandudey** [comment]
Fixed, link will be updated once `dev` gets merged to `master`, thanks!

**Comment by GlenCooper** [comment]
Confirmed fixed.  Thanks
