### ISSUE TITLE
[Tracking] Verify that we comply with the coding style.

### ISSUE THREAD

**Issue by jeandudey** [btcven/turpial-firmware#139]
We need to do a cleanup of the code and follow the overall guidelines at [CONTRIBUTING.md](https://github.com/btcven/turpial-firmware/blob/master/CONTRIBUTING.md).

This can be done progressively.

- `components/ESC`.
- `components/HMI`.
- `components/HTTP`.
- `components/Network`.
- `components/NVS`.
- `components/Radio`.
- `components/Task`.
- `components/Util`

**Comment by luisan00** [comment]
* `components/HTTP done by @xkevin190 in PR #147

**Comment by luisan00** [comment]
linked with PR #148
