### ISSUE TITLE
Implement HTTP Authentication

### ISSUE THREAD

**Issue by jeandudey** [btcven/turpial-firmware#140]
We need to authenticate HTTP requests, so _only_ the administrator can change the configuration.

What we need:

- Endpoint to change user/pass (`/system/credentials` probable URI).
  - Store the credentials on NVS.
- Wait for espressif/esp-idf#4823 to get merged (HTTP authentication).
- Use basic authentication (for now).

**Comment by luisan00** [comment]
Basic Auth. was done by @xkevin190 in PR #141

**Comment by luisan00** [comment]
Linked PR #141
