### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by gustavosinbandera1** [btcven/turpial-firmware#176]
**Describe the bug**
I have cloned the repo and all looks ok, when I execute ```make BOARD=esp32-wrover-kit```` or whatever other esp32 platform, I amgetting this output

```

```
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/boards/esp32-wrover-kit
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/boards/common/esp32
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/core
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/cpu/esp32
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/cpu/esp32/freertos
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/cpu/esp32/periph
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/cpu/esp32/vendor
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/cpu/esp32/vendor/esp-idf
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/cpu/esp32/vendor/esp-idf/driver
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/cpu/esp32/vendor/esp-idf/esp32
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/cpu/esp32/vendor/esp-idf/heap
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/cpu/esp32/vendor/esp-idf/nvs_flash
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/cpu/esp32/vendor/esp-idf/soc
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/cpu/esp32/vendor/esp-idf/spi_flash
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/cpu/esp32/vendor/esp-idf/wpa_supplicant
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/cpu/esp32/vendor/esp-idf/wpa_supplicant/port
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/cpu/esp32/vendor/esp-idf/wpa_supplicant/src/crypto
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/cpu/esp_common
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/cpu/esp_common/esp-now
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/cpu/esp_common/freertos
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/cpu/esp_common/periph
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/cpu/esp_common/vendor
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/cpu/esp_common/vendor/xtensa
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/drivers
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/drivers/mtd
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/drivers/periph_common
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/drivers/slipdev
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/auto_init
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/div
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/event
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/evtimer
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/fmt
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/isrpipe
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/log
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/luid
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/net/application_layer/gcoap
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/net/application_layer/nanocoap
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/net/crosslayer/inet_csum
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/net/crosslayer/netopt
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/net/gnrc
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/net/gnrc/netapi
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/net/gnrc/netif
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/net/gnrc/netif/hdr
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/net/gnrc/netif/init_devs
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/net/gnrc/netreg
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/net/gnrc/network_layer/icmpv6
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/net/gnrc/network_layer/icmpv6/echo
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/net/gnrc/network_layer/ipv6
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/net/gnrc/network_layer/ipv6/hdr
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/net/gnrc/network_layer/ipv6/nib
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/net/gnrc/network_layer/ndp
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/net/gnrc/network_layer/sixlowpan
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/net/gnrc/network_layer/sixlowpan/ctx
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/net/gnrc/network_layer/sixlowpan/frag
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/net/gnrc/network_layer/sixlowpan/frag/fb
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/net/gnrc/network_layer/sixlowpan/frag/rb
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/net/gnrc/network_layer/sixlowpan/iphc
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/net/gnrc/network_layer/sixlowpan/nd
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/net/gnrc/pkt
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/net/gnrc/pktbuf
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/net/gnrc/pktbuf_static
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/net/gnrc/pktdump
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/net/gnrc/sock
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/net/gnrc/sock/udp
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/net/gnrc/transport_layer/udp
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/net/link_layer/l2util
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/net/netif
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/net/network_layer/icmpv6
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/net/network_layer/ipv6/addr
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/net/network_layer/ipv6/hdr
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/net/network_layer/sixlowpan
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/net/sock
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/net/sock/async/event
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/net/transport_layer/udp
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/newlib_syscalls_default
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/od
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/pm_layered
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/posix/inet
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/posix/pthread
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/ps
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/random
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/random/tinymt32
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/shell
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/shell/commands
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/stdio_uart
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/timex
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/tsrb
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/RIOT/sys/xtimer
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/sys
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/sys/cjson
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/sys/net
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/sys/net/coap
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/sys/net/vaina
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/sys/storage
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/sys/storage/nvs
"make" -C /home/gustavosinbandera1/TEXAS/turpial-firmware/sys/storage/settings

/turpial-firmware/bin/esp32-wrover-kit/esp_wifi_ap.a: No such file or directory
make: ***
```

RIOT module master branch
 - OS: Ubuntu 18.04
- turpial firmware dev and master  branch

**Comment by luisan00** [comment]
That error occurs when the RIOT module is not updated.

You need to init and update modules as described  in: 
https://github.com/btcven/turpial-firmware#compiling

**Comment by luisan00** [comment]
Closing due to invalid
