### ISSUE TITLE
Use a Kconfig based style configuration menu (menuconfig).

### ISSUE THREAD

**Issue by jeandudey** [btcven/turpial-firmware#81]
Currently we use the defaults.h file, but it's unergonomic.

- Basic Kconfig file is #142

**Comment by luisan00** [comment]
Don't stale

**Comment by jeandudey** [comment]
#142 Is on going

**Comment by jeandudey** [comment]
Oops, closed by error.

**Comment by jeandudey** [comment]
Kconfig can be used to configure the firmware. Closing.
