### ISSUE TITLE
Radio communication.

### ISSUE THREAD

**Issue by jeandudey** [btcven/turpial-firmware#86]
## Description

The device should be able to connect to other nodes. Send packets, and route packets between nodes.

## Radio

Currently we use the CC1312 radio MCU to communicate with other nodes, this radio communicates with the ESP32 using UART. As of today, the pins used are defined in the `defaults.h` file, however these aren't the pins we'll be going to use for the finished Turpial board and are there just for development purposes.

## Radio UART Protocol

We need to research and implement a new protocol to communicate with both MCUs, the way to send packets to the network, figure out how to request a route and such things.

## Radio Routing

To route packets over the network we'll be using AODV over IPv6.

**Comment by luisan00** [comment]
Communication between esp32 and radio module *- options -*

* **SLIP** *- Serial Line Internet Protocol -*
  - https://tools.ietf.org/html/rfc1055

* **CSLIP** *- Compressed SLIP -*
  - https://tools.ietf.org/html/rfc1144

* **KISS** *- keep it simple, stupid -*
  - https://en.wikipedia.org/wiki/KISS_(TNC)

* Modbus RTU
  - https://www.rtautomation.com/technologies/modbus-rtu/
  - https://ipc2u.com/articles/knowledge-base/modbus-rtu-made-simple-with-detailed-descriptions-and-examples

More related links  
https://docs.espressif.com/projects/esp-idf/en/release-v4.0/api-reference/protocols/modbus.html

**Comment by jeandudey** [comment]
I'll close this as we already communicate with the radio through SLIP.
